docs: add note about how to determine new accessibility supported
dequelabs/axe-core pull request #2536
Opened 2020-10-01 19:56 UTC by straker

Adds note about how we determine what new screen readers, browsers, or environments we accessibly support and add JAWS/Chrome as an accessibility supported combination.

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Follows the commit message policy, appropriate for next version
- [ ] Code is reviewed for security

2020-10-02 10:45 UTC, WilcoFiers requested changes

2020-10-02 10:45 UTC, WilcoFiers commented on doc/accessibility-supported.md
> +Boiled-down, accessibility supported means that in order for a technique to be valid, it must work on all viable platforms for all assistive technology that are widely used and freely available (para
```suggestion
Accessibility supported means that in order for a technique to pass, it must work in some predefined set of browsers and assistive technologies. For axe-core this means that for a screen reader, browser, or environment to be added to the list of supported combinations, the following two criteria must be met:
```

2020-10-07 13:57 UTC, dylanb approved these changes

2020-10-07 13:57 UTC, WilcoFiers approved these changes

2020-10-07 14:23 UTC, merged