feat(standards): add superclassRole to ariaRoles
dequelabs/axe-core pull request #2600
Opened 2020-10-27 20:21 UTC by redgardner

Added superclassRole attributes as an array of strings per WAI-ARIA 1.1 spec

Closes issue 2151

Added superclassRole to each aria-role per WAI-ARIA 1.1 spec

Closes issue:

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Follows the commit message policy, appropriate for next version
- [ ] Code is reviewed for security

2020-10-27 20:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dequelabs/axe-core?pullRequest=2600) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dequelabs/axe-core?pullRequest=2600) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dequelabs/axe-core?pullRequest=2600) it.</sub>

2020-10-27 21:34 UTC, straker commented
Thanks for the pr. Would you be able to add the `superclassRole` to the ARIA 1.2 roles as well? For example [insertion](https://www.w3.org/TR/wai-aria-1.2/#insertion)

2020-10-27 21:43 UTC, redgardner commented
Sure thing! I'll make this update

2020-10-27 21:56 UTC, redgardner commented
Made the update. Is it correct to wait to squash these commits until merge to develop?

2020-10-27 22:06 UTC, straker commented
Yep. We'll squash the commit on our side so you don't have to worry about it.

2020-10-28 11:10 UTC, WilcoFiers requested changes
Couple minor edits. Should be good to go after that.

2020-10-28 11:10 UTC, WilcoFiers commented on lib/standards/aria-roles.js
> +		superclassRole: ['section'],
```suggestion
		superclassRole: ['section'],
		// Note: spec difference
```

2020-10-28 13:57 UTC, redgardner commented on lib/standards/aria-roles.js
> +		superclassRole: ['section'],
Resolved this with the latest push and a few more areas where I had done this

2020-10-28 13:57 UTC, redgardner commented on lib/standards/aria-roles.js
> +		superclassRole: ['section']
Fixed

2020-10-28 13:58 UTC, redgardner commented on lib/standards/aria-roles.js
> +		superclassRole: ['structure', 'widget', 'window']
Whoops. Thanks for the catch

2020-10-28 13:58 UTC, redgardner commented on lib/standards/aria-roles.js
> +		superclassRole: ['section'],
Fixed along with a few others I found

2020-10-28 13:59 UTC, redgardner commented
Thanks I've addressed all the feedback and pushed up a new commit. I wasn't sure if that was the preferred way or accepting change recommendation.

2020-10-29 10:01 UTC, WilcoFiers approved these changes

2020-10-29 10:05 UTC, WilcoFiers commented
@redgardner can you please click to sign the CLA. The link is https://cla-assistant.io/dequelabs/axe-core?pullRequest=2600

2020-10-29 14:04 UTC, redgardner commented
@WilcoFiers I have tried to sign the CLA in multiple browsers and windows. I've gotten confirmation that I've signed it, but I keep getting the pending CLA note. 

I've tried hitting the recheck as well. Is there something else to try?

2020-10-30 10:16 UTC, WilcoFiers commented
@redgardner I'm not sure what's going on with the CLA site. We've been having some issues. I'll take your message as confirmation you agree, and will merge the pull request. Thank you very much for this contribution!

2020-10-30 10:18 UTC, merged

2020-10-30 15:00 UTC, redgardner commented
Thanks! Sorry for the hassle with the CLA stuff. I agree with the CLA.