core(cleanup): core/lib/imports: remove core-js and core-js-pure dependencies
dequelabs/axe-core pull request #2637
Opened 2020-11-12 23:17 UTC by jayaddison

These polyfills, previously provided by `core-js` / `core-js-pure`, can also be fulfilled by existing bundled dependencies within `axe-core`.

In particular:

- `es6-promise` can provide `Promise`
- `typedarray` can provide `Uint32Array` (and was an implicit dependency, but is now added to `package.json` explicitly)
- `weakmap-polyfill` can provide `WeakMap`

This *might* provide an opportunity to remove `core-js` and `core-js-pure` completely from `axe-core`'s dependencies.

Unit tests pass **intermittently** locally, so additional verification would definitely help.  In particular, `UnhandledPromiseRejectionWarning` exceptions appear to be thrown unpredictably from the headless browser environment.

**Build Size Impact**

Before @ 3c2429b4032d29cdcfd3083e46e91854dccd733b
```sh
$ npm run-script build
...
./axe.min.js
Size:		419.95 Kb
Gzip Size:	108.92 Kb

Done.
```

After @ a9aebc21675611779b2a396ea50b7e07d36b9ec5 (this changeset)
```sh
$ npm run-script build
...
./axe.min.js
Size:		406.84 Kb
Gzip Size:	103.71 Kb

Done.
```

Relates to #1935

TODO:

- [ ] Investigate flaky tests due to unhandled promise rejections

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Follows the commit message policy, appropriate for next version
- [ ] Code is reviewed for security

2020-11-12 23:26 UTC, straker commented
Sweet! Love seeing more file size reduction. I'll take a look at this more in-depth probably tomorrow. 

One thing to note though is the if statement we had around the `Promise` polyfill was to ensure that if someone else had loaded a promise library we didn't override it, which was the problem in https://github.com/dequelabs/axe-core/issues/1468. Unless `es6-promise` has changed how it loads the polyfill we'll probably still need to keep that check in as that was the fix in https://github.com/dequelabs/axe-core/pull/1470/files.

2020-11-12 23:29 UTC, jayaddison commented
Ah, great context - thanks @straker!  I hope I'm not incorrectly taking the code backwards given that `es6-promise` was in use previously; I didn't realize that.  Anyway, I'll restore that conditional check here.

2020-11-12 23:35 UTC, jayaddison commented
(and now I wonder whether `typedarray` is also potentially clobbering native `Uint32Array` implementations when present.  `weakmap-polyfill` claims to check for a native version before polyfilling, but I'm not sure about `typedarray` based on the source)

2020-11-16 18:03 UTC, straker requested changes

2020-11-16 18:03 UTC, straker commented on lib/core/imports/index.js
I believe this block is no longer need. It looks like weakmap-polyfill checks if `self.WeakMap` exists before doing anything and then sets it on the global `self` itself. https://github.com/polygonplanet/weakmap-polyfill/blob/master/weakmap-polyfill.js#L11-L28

```suggestion
```

2020-11-16 18:13 UTC, straker approved these changes
Tested `typedarray` with the following code in node and it does not add the `Unit32Array` to the global namespace, so we should be safe to import it in.

```js
delete global.Uint32Array;

var typedarray = require("typedarray");
var Uint32ArrayPolyfill = typedarray.Uint32Array;

console.log(global.Uint32Array);  // undefined
console.log(Uint32Array);  // error
```

2020-11-16 21:01 UTC, merged

2020-11-18 14:57 UTC, jayaddison commented
Nice - thanks!  I wasn't able to reproduce the flaky tests I'd been experiencing locally; but if tests happen to fail more regularly (particularly related to `UnhandledPromiseRejectionWarning`), please do consider this for a revert.