tests: fix?
dequelabs/axe-core pull request #2670
Opened 2020-11-30 17:34 UTC by straker

Chrome is [failing to start a lot](https://app.circleci.com/pipelines/github/dequelabs/axe-core/1479/workflows/c9511638-cba6-4217-b2b5-2a5efa5b1fa2/jobs/24819) and with no apparent reason as this was all working fine when running it as Grunt. This is a copied/pasted file that worked before but now fails. Trying this to see if it resolves the issues as suggested in various sites.

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Follows the commit message policy, appropriate for next version
- [ ] Code is reviewed for security

2020-12-01 16:29 UTC, straker commented
Alright. So after trying every combination of things suggested by the interwebs to fix this, the only thing that finally has worked consistently is to use chrome headless. I have stopped and restarted the job about 6 or 7 times now and it has yet to fail to start. I don't understand it but here we are.

2020-12-02 16:12 UTC, WilcoFiers requested changes

2020-12-02 16:12 UTC, WilcoFiers commented on test/integration/full/test-webdriver.js
> -var isCI = require('is-ci');
Looks like we can then drop this dependency.

2020-12-03 09:54 UTC, WilcoFiers approved these changes

2020-12-03 15:15 UTC, merged