feat(role-text): add role-text rule
dequelabs/axe-core pull request #2702
Opened 2020-12-18 17:27 UTC by straker

Add support for `role=text` only if the contents do not have focusable descendants. This is very similar to our new `nested-interactive` rule except that instead of focusing on interactive roles this focuses on making sure the `text` role is used in such a way that does not override the semantics of the children.

Now we could have made `role=text` also have `childrenPresentational: true`, but that means it would have thrown errors with the `nested-interactive` rule which didn't make much sense (it's not really an interactive component). 

Closes issue: #1597

2020-12-18 17:33 UTC, straker commented on doc/rule-descriptions.md
> -| [nested-interactive](https://dequeuniversity.com/rules/axe/4.1/nested-interactive?application=RuleDescription)                                   | Ensure interactive controls are not nested
Not sure how this ended up in the wrong place.

2020-12-21 11:49 UTC, WilcoFiers requested changes

2020-12-21 11:49 UTC, WilcoFiers commented on lib/rules/aria-text.json
> +    "help": "\"role=text\" should only be used on elements with no focusable descendants"
Help test should be shorter than the description.

```suggestion
    "help": "Do not use \"role=text\" on elements with no focusable descendants"
```

2020-12-21 11:49 UTC, WilcoFiers commented on lib/rules/aria-text.json
> +    "description": "Ensures \"role=text\" is used correctly",
This should probably be a little more descriptive.

2021-01-11 11:01 UTC, WilcoFiers approved these changes

2021-01-11 15:08 UTC, merged