feat(aria-label): new rule to flag incorrect use of aria-label
dequelabs/axe-core pull request #2712
Opened 2020-12-22 00:27 UTC by straker

Closes issue: #1575

2020-12-28 10:44 UTC, WilcoFiers commented on lib/rules/aria-label.json
> +    "help": "Use aria-label, aria-labelledby, and aria-describedby on elements with non-static roles"
I'd like to see some test data on this. What is the problem we are solving with this rule?

2020-12-28 10:46 UTC, WilcoFiers requested changes
We're going to need to run this rule by the JC. Can you do some testing for this to show what the problem is that comes from this? I suspect we're going to get complaints about this one.

2021-01-12 18:57 UTC, straker commented
I think this PR is not needed and we should instead use the [Prohibited States and Props from ARIA 1.2](https://www.w3.org/TR/wai-aria-1.2/#prohibitedattributes) as they cover this exact use case but in a more generic way.

Related discussions:
- https://github.com/w3c/aria/issues/756
- https://github.com/w3c/aria/pull/985

2021-01-12 18:57 UTC, closed without merging

2021-01-13 17:58 UTC, straker commented
Note, this may not work with the `<i>` attribute as it doesn't have a role mapping. I will do some testing `aria-label` on different elements to see how screen readers handle it.

2021-01-13 18:24 UTC, straker commented
From Scott O'Hara on asking about HTML elements with no role mapping:

> no mapping = generic
> generic doesn't allow naming

2021-01-13 20:53 UTC, straker commented
Tested the following DOM in different browsers:

```html
<div aria-label="my label">foo</div>
<span aria-label="my label">foo</span>
<i aria-label="my label">foo</i>
<p aria-label="my label">foo</p>

<div aria-labelledby="label">foo</div>
<span aria-labelledby="label">foo</span>
<i aria-labelledby="label">foo</i>
<p aria-labelledby="label">foo</p>
```

No browser / screen reader combination read the `aria-label` or the `aria-labelledby` attributes. All names returned as "foo"