fix(aria-allowed-attr): error when generic elements use aria-label and aria-labelledy
dequelabs/axe-core pull request #2766
Opened 2021-01-19 21:01 UTC by straker

**Note:** The "proper" way to handle this would be if axe-core returned `generic` instead of `null` for nodes without a role. However, we are not set up to do that and It would require going through all use cases where we check for `null` role and changing it for `generic`. I'm not sure we want to do that just yet, but we should at least add a tech debt ticket to do so if this is merged.

Closes issue: #1575

2021-01-19 21:08 UTC, straker commented on test/commons/standards/get-aria-roles-by-type.js
> +  it('should return a list of role names by type', function() {
I got tired of updating this test when adding new roles. This should allow us to not have it change so often.

2021-01-20 20:21 UTC, WilcoFiers commented on lib/checks/aria/aria-prohibited-attr-evaluate.js
> +  const role = getRole(virtualNode) || 'generic';
I'm not so sure I agree with that suggestion of Scott, nor with the implication of it. I don't think we should call every use of aria-label on an element we don't have a role for as a failure of SC 4.1.2. That seems a bit of a stretch to me. A best practice might be more appropriate. I'm going to get some more Deque folks to weigh in on that one first.

2021-01-27 13:01 UTC, WilcoFiers requested changes

2021-01-27 13:01 UTC, WilcoFiers commented on test/checks/aria/aria-prohibited-attr.js
> +describe('aria-prohibited-attr', function() {
Huh, odd.

2021-02-10 10:11 UTC, WilcoFiers requested changes

2021-02-10 10:11 UTC, WilcoFiers commented on test/integration/rules/aria-allowed-attr/failures.html
> +<div aria-labelledby="value" id="fail24"></div>
Add some incomplete examples too please.

2021-02-10 10:11 UTC, WilcoFiers commented on lib/checks/aria/aria-prohibited-attr-evaluate.js
> +  const prohibitedAttrs = role
Apologies for not thinking of this sooner, but I think this should check if this is a "null" attribute. Don't think this should complain about `<div aria-label=" " aria-labelledby="doesNotExist">`.

2021-02-26 13:10 UTC, WilcoFiers requested changes
Very minor tweak.

2021-02-26 13:10 UTC, WilcoFiers commented on lib/checks/aria/aria-prohibited-attr-evaluate.js
> +      }
```suggestion
    if (!role && sanitize(subtreeText(virtualNode)) !== '') {
      return undefined;
```

2021-03-04 20:27 UTC, straker commented on .circleci/config.yml
> +      - v9-cache-unix-{{ checksum "package-lock.json" }}
In order to get the tests working again we had to update our version of chromedriver. However, just updating the `packge-lock.json` file didn't work as we checksum the `package.json` file. This also means security updates that just modify the package-lock file do not cause our builds to use the latest versions.

2021-03-04 20:27 UTC, straker commented on .circleci/config.yml
> -      # test examples
Removed as we did in master as windows / chrome was broken.

2021-03-05 10:14 UTC, WilcoFiers approved these changes

2021-03-05 16:53 UTC, merged