tests: put back autocomplete-valid act tests
dequelabs/axe-core pull request #2997
Opened 2021-06-15 16:43 UTC by straker

https://github.com/act-rules/act-rules.github.io/pull/1583 was merged.

Closes issue: #2960

2021-08-12 20:08 UTC, straker commented
Had to not use the CircleCi cache in order to get the latest version of act rules since updates don't modify the package-lock.

2021-08-16 08:33 UTC, WilcoFiers requested changes

2021-08-16 08:33 UTC, WilcoFiers commented on .circleci/config.yml
> +      - run: npm install
I'm not so sure this is the right thing to do here Steve.

2021-08-16 08:33 UTC, WilcoFiers commented on .circleci/config.yml
> +      - run: npm install
What about doing it this way instead?

```suggestion
      - <<: *restore_dependency_cache_unix
      # Always run on the latest master branch, regardless of cache
      - run: npm install act-rules/act-rules.github.io#master
```

2021-08-18 15:56 UTC, WilcoFiers approved these changes

2021-08-18 16:10 UTC, merged