chore(d.ts): type runPartial + finishRun
dequelabs/axe-core pull request #3066
Opened 2021-07-07 17:30 UTC by WilcoFiers

Add types for:

- axe.utils.getFrameContexts
- axe.runPartial
- axe.finishRun

Related to #3059

2021-07-07 20:31 UTC, straker requested changes

2021-07-07 20:31 UTC, straker commented on axe.d.ts
> +    ancestry: number[],
These all should be strings, and `selector` and `ancestry` should account for shadow DOM iframes.

```suggestion
    selector: Selector,
    xpath: string[],
    ancestry: Selector,
```

2021-07-07 20:31 UTC, straker commented on axe.d.ts
> +    getFrameContexts: (context: ElementContext | null) => FrameContext[]
```suggestion
    getFrameContexts: (context?: ElementContext) => FrameContext[]
```

2021-07-07 21:05 UTC, stephenmathieson requested changes

2021-07-07 21:05 UTC, stephenmathieson commented on axe.d.ts
> +    nodes: object[],
The `object` type is extremely difficult to use/not what we want.

```suggestion
    nodes: Array<Record<string, unknown>>,
```

2021-07-08 11:40 UTC, stephenmathieson submitted a review, later dismissed
LGTM. Should wait for @straker for the final OK though

2021-07-08 14:35 UTC, straker approved these changes

2021-07-08 16:58 UTC, stephenmathieson approved these changes

2021-07-09 15:12 UTC, straker approved these changes

2021-07-09 16:09 UTC, merged