fix: check for hidden elements on `aria-errormessage`
dequelabs/axe-core pull request #3156
Opened 2021-09-13 20:13 UTC by Zidious

Check if hidden elements are present on `aria-errormessage` via `isVisible()` and add tests.

Closes issue: https://github.com/dequelabs/axe-core/issues/3149

2021-09-20 15:21 UTC, WilcoFiers requested changes
I feel like adding at least one integration test here would be a good idea.

2021-09-20 15:21 UTC, WilcoFiers commented on lib/checks/aria/aria-errormessage-evaluate.js
> +      if (!isVisible(idref)) {
You'll want to check that it's visible to screen readers, not that it's on screen:

```suggestion
      if (!isVisible(idref, true)) {
```

Please add tests checking that off screen messages don't error, and that a message with aria-hidden on it does.

2021-09-22 15:56 UTC, WilcoFiers requested changes
Very minor stuff.

2021-09-22 15:56 UTC, WilcoFiers commented on test/checks/aria/errormessage.js
> +      '<div><input type="text" id="target" aria-invalid="true" aria-errormessage="id-message-1"></div>' +
Why do you need the div?

2021-09-22 15:56 UTC, WilcoFiers commented on test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
> +
Can you add an example with a hidden error, that passes because it has aria-invalid="false"?

2021-09-22 16:26 UTC, Zidious commented on test/checks/aria/errormessage.js
> +      '<div><input type="text" id="target" aria-invalid="true" aria-errormessage="id-message-1"></div>' +
Good find

2021-09-23 15:43 UTC, WilcoFiers requested changes

2021-09-23 15:43 UTC, WilcoFiers commented on test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
> +      aria-errormessage="pass68"
That's not a hidden element.

2021-09-23 15:43 UTC, WilcoFiers commented on test/checks/aria/errormessage.js
> +    console.log(checkContext._data);
This

2021-09-23 16:38 UTC, Zidious commented on test/integration/rules/aria-valid-attr-value/aria-valid-attr-value.html
> +      aria-errormessage="pass68"
Ah, I see it, good catch.

2021-09-24 15:15 UTC, WilcoFiers approved these changes

2021-09-24 15:33 UTC, merged