chore: hidden and aria-hidden for nested-interactive
dequelabs/axe-core pull request #3159
Opened 2021-09-15 13:51 UTC by oscarmarina

The standard technique for hiding content for all users has been the use CSS display:none. Now, both ARIA and HTML5 also provide a semantic indication of content state that indicates content is hidden or should not be available to users

- [HTML5 Accessibility Chops: hidden and aria-hidden - Steve Faulkner](https://www.tpgi.com/html5-accessibility-chops-hidden-and-aria-hidden/)
- [The state of hidden content support in 2016 - Steve Faulkner](https://www.tpgi.com/the-state-of-hidden-content-support-in-2016/)

In nested interactive controls they would have the same behavior if hidden pass the test; aria-hidden=true test would behave in the same way

2021-09-15 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dequelabs/axe-core?pullRequest=3159) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dequelabs/axe-core?pullRequest=3159) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dequelabs/axe-core?pullRequest=3159) it.</sub>

2021-09-15 16:06 UTC, straker commented
Thanks for the pr. Unfortunately I don't think this works as expected. Using `display: none` removes the element both visually and from the tab order, while `aria-hidden` does neither of those. Testing this out in different screen reader / browser combinations:

```html
<div role="button"><button aria-label="true">My Button</button></div>
```

- IE / JAWS - Can tab to the button and is read as "Unlabeled 0 button"
- Edge / JAWS - Can tab to the button and is read as "My Button, button", activating the button moves focus off of it
- FireFox / NVDA - Can tab to the button and nothing is read out, sometimes just "blank"
- Safari / VO - Can tab to the button and is read as "button" (no label). Furthermore you can press "down" to enter the text and "My Button" is read.

2021-09-16 06:09 UTC, oscarmarina commented
I agree the correct combination would be `aria-hidden="true"` and `tabindex="-1"` as explainend in
 [accessibilityinsights.io → aria-hidden-focus](https://accessibilityinsights.io/info-examples/web/aria-hidden-focus/)

- Element with aria-hidden="true" contains only focusable elements that are disabled or not tabbable


For me this is a variant of the same thing but I don't know if you shared this opinion.

2021-09-16 15:27 UTC, straker commented
So talking with Wilco we determined that since the example fails `aria-command-name` and `aria-hidden-focus`, it doesn't also need to fail `nested-interactive`. Furthermore, since the description of the rule is `Nested interactive controls are not announced by screen readers`, adding `aria-hidden=true` passes this description as the button is no longer announced to a screen reader.

2021-09-16 15:29 UTC, straker requested changes
You'll also need to edit https://github.com/dequelabs/axe-core/blob/develop/test/integration/rules/nested-interactive/nested-interactive.json and add the new `ids` to the list of fail / passes.

2021-09-16 15:29 UTC, straker commented on test/integration/rules/nested-interactive/nested-interactive.html
> +<div role="button" id="pass6"><button aria-hidden="true" tabindex="-1">pass</button></div>
There's already an `id="pass6"` on line 10.

```suggestion
<div role="button" id="pass7"><button aria-hidden="true" tabindex="-1">pass</button></div>
```

2021-09-17 12:49 UTC, scottaohara commented
Tested the following snippet with a colleague the other day - with Dragon both checkboxes in the following markup snippet were still exposed;
```html
<div role=checkbox aria-checked=true tabindex=0 aria-label=foo>
  <input type=checkbox aria-hidden=true tabindex=-1> <!-- visually hidden -->
</div>
```
Using VoiceOver and the down arrow key alone to read line-by-line, the visually hidden checkbox is still reached, causing a focus stop without an announcement.

While screen readers are trying to error correct for author blunders like these, it's not bullet proof across all other AT - more of which still needs testing.   I'd request that this be taken into consideration before passing stuff that can still pose issues, and would not discourage authors from poor coding practices.

Thanks

2021-09-23 12:05 UTC, WilcoFiers commented
Apologies for the slowed response. I've been a little reluctant to dive into this. Scott is right in that this pattern just doesn't work very well, and that you probably just shouldn't use it.

I think what needs to happen is that we create a new failure message, specifically to explain that using negative tabindex can still cause problems. I'll create an issue for this.

2021-11-04 21:28 UTC, straker commented
I believe this pr is replaced by https://github.com/dequelabs/axe-core/pull/3194, since we don't want tabindex=-1 to pass but now warn of the problem.

2021-11-05 17:22 UTC, straker commented
Going to close this issue. Negative tabindex will now produce a warning stating that it won't prevent assistive technologies from focusing the element. In terms of the number of rule failures, I believe all 3 should be reported for the following reasons:

If the user starts with this HTML:

```html
<div role="button"><button aria-hidden="true">My Button</button></div>
```

We report 3 failures: `aria-hidden-focus`, `button-name`, and `nested-interactive`. So the user then does this:

```html
<div role="button" aria-label="My Button"><button tabindex="-1" aria-hidden="true">My Button</button></div>
```

Which should correctly produce a `nested-interactive` failure with the message warning of `tabindex=-1`. If we were to prevent `nested-interactive`, we'd first have to know what other rules failed, which we can't do. So it's better that all 3 fail the first time as they are all 3 different problems on the structure.

2021-11-05 17:22 UTC, closed without merging