fix(aria-allowed-role): remove role allowances for embed, iframe and object
dequelabs/axe-core pull request #3265
Opened 2021-11-08 13:24 UTC by scottaohara

closes #3264

remove role allowances for `iframe`, `embed` and `object` per https://github.com/w3c/html-aria/pull/370

2021-11-09 22:07 UTC, straker commented
Thanks for the pr. Because this is removing roles we'll probably need to make this at least a `feat`, but it also might be a breaking change? @WilcoFiers will need to decide how we want to pull this in.

2021-11-09 23:45 UTC, scottaohara commented
thanks @straker.  In the future, if you would rather I just create issues and not PRs, I'm happy to do that. The intent is to help with the work, not create extra. So if I'm doing that, please let me know and I'll stop :)

2021-11-10 12:13 UTC, WilcoFiers requested changes
I left a review on the ARIA in HTML PR explaining why I disagree with these changes. Lets discuss there.

2021-11-10 15:11 UTC, straker commented
@scottaohara I think any changes in ARIA that add new roles are good for prs. Changes that remove roles should probably be issues since we'll want to make sure we don't break users before we're ready.

2022-01-10 16:57 UTC, WilcoFiers commented
I'm going to close this, since the proposal is getting reworked. We can reopen the PR, or create a new one once there's an updated proposal. Again, these PRs are really appreciated Scott!

2022-01-10 16:57 UTC, closed without merging