adds role=radio to img alt=foo allowances
dequelabs/axe-core pull request #3320
Opened 2021-12-03 11:46 UTC by scottaohara

A `role=radio` was meant to be an allowance for an `img alt=foo`, but it had mistakenly been left out of the spec.
ARIA in HTML is fixing this oversight, https://github.com/w3c/html-aria/pull/381, so this PR is to match this added allowance.

2021-12-09 17:15 UTC, WilcoFiers requested changes
Thanks Scott. Would you be up for adding a passing integration test for this?

https://github.com/dequelabs/axe-core/tree/develop/test/integration/rules/aria-allowed-attr

2021-12-09 20:24 UTC, scottaohara commented
@WilcoFiers would this be a new type of integration test then?  it looks like what's in that folder now is divs with allowed roles and attributes.  but this change is for the img element role allowances.  maybe i'm missing something here.

2021-12-13 15:25 UTC, WilcoFiers commented
@scottaohara You are right. Apologies. I added the wrong link. This is about what roles are allowed, not what attributes:
https://github.com/dequelabs/axe-core/tree/develop/test/integration/rules/aria-allowed-role

2021-12-13 17:09 UTC, WilcoFiers approved these changes
LGTM. Thank you again @scottaohara!

For the books; I reviewed this PR for security.

2021-12-13 17:10 UTC, merged