Update allowed button & input type=button roles
dequelabs/axe-core pull request #3354
Opened 2022-01-16 16:18 UTC by scottaohara

closes #3353

- Adds `role=combobox` to the `<button>` element.
- Adds `role=combobox` and `role=checkbox` to the `<input type=button>` element.

2022-01-17 10:35 UTC, WilcoFiers requested changes
We'll need integration tests for aria-allowed-role.

2022-11-22 16:42 UTC, straker commented
We seem to have let this pr fall into the cracks. Going to update it a bit to make sure it's ready for review again.

2022-11-28 17:29 UTC, WilcoFiers approved these changes

2022-11-28 17:32 UTC, WilcoFiers commented
[x] Reviewed for security

2022-11-29 16:08 UTC, merged