fix(deprecatedrole,color-contrast): fix message to properly include deprecated role, improve color-contrast pass messages
dequelabs/axe-core pull request #3387
Opened 2022-02-07 17:02 UTC by straker

Missed during review (my fault) that `data.values` wouldn't work for non-array `data` string. Might try my hand at extending our [check message validation script](https://github.com/dequelabs/axe-core/blob/develop/test/testutils.js#L443) to include verifying that the data object matches all interpolated parts of the string (probably using [process-message](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/process-message.js))

Closes issue: #3384

2022-02-08 10:41 UTC, WilcoFiers requested changes
I was thinking about this the other day. We don't really have a way to test this, which has caused a few issues. How about if we add something to `testUtils.MockCheckContext` that lets us write tests for these messages?

2022-02-18 17:53 UTC, straker commented
Doing this revealed that color-contrast had a few pass cases where the message wasn't passed any data. Fixed those with the test.

2022-02-24 13:48 UTC, WilcoFiers submitted a review, later dismissed
LGTM, just update the title, since you're not just touching deprecatedrole.

2022-02-28 11:13 UTC, WilcoFiers approved these changes

2022-02-28 16:09 UTC, merged