fix(avoid-inline-spacing): add spacing threshold
dequelabs/axe-core pull request #3533
Opened 2022-07-05 10:39 UTC by WilcoFiers

- Replaces the avoid-inline-styling check three new checks, one for each CSS property
- Add a important-css-property evaluate method
- Enable ACT rule tests related to the avoid-inline-spacing axe-core rule
- For the line-height property, only fail multi-line texts

Closes issue: https://github.com/dequelabs/axe-core/issues/3467

2022-07-20 14:56 UTC, stephenmathieson commented on lib/checks/shared/inline-style-property-evaluate.js
> + * Check if a CSS property
```suggestion
 * Check if a CSS property [does/has something]
```

2022-07-20 20:40 UTC, straker requested changes

2022-07-20 20:40 UTC, straker commented on lib/commons/text/get-line-count.js
> +/**
Missing tests for `get-line-count`

2022-07-20 20:40 UTC, straker commented on lib/commons/text/get-line-count.js
> +export default function getLineCount(domNode, margin = 2) {
This function could be simplified to something like `isMultilineText` and then return if `range.getClientRects() > 1`. Calculating the exact number of lines is not necessary and could be error prone. All we really need to know is if there is more than 1 line.

2022-07-21 23:46 UTC, WilcoFiers commented on lib/commons/text/get-line-count.js
> +/**
Whaaaa??? I swear I wrote those :-/

2022-07-21 23:49 UTC, WilcoFiers commented on test/checks/shared/inline-style-property.js
> +    (isIE11 ? xit : it)('is false when below 1.5em and !important', function () {
Beat me... IE reported the value as 0.19. Guess IE just cannot count. Didn't think it worth debugging since we're pulling IE soon.

2022-07-21 23:49 UTC, WilcoFiers commented on test/integration/rules/avoid-inline-spacing/avoid-inline-spacing.html
> +<p id="pass6" style="line-height: 1.5em !important;">Banana<br>pass</p>
Seems reasonably well handled by the check test. What's the benefit?

2022-08-08 08:20 UTC, WilcoFiers commented on lib/checks/shared/inline-style-property-evaluate.js
> +    return 0;
Good catch. Yeah line-height shouldn't be 0.

2022-08-08 10:14 UTC, WilcoFiers commented on test/integration/rules/avoid-inline-spacing/avoid-inline-spacing.html
> +<!-- CSS keywords -->
I didn't add "initial", since IE chokes on that.

2022-08-08 20:51 UTC, straker approved these changes

2022-08-09 09:19 UTC, merged