feat(aria-required-children): add aria-busy check
dequelabs/axe-core pull request #3569
Opened 2022-07-27 17:06 UTC by pschwendy

Closes issue: #3208

2022-07-28 20:33 UTC, straker requested changes

2022-07-28 20:33 UTC, straker commented on test/checks/aria/aria-busy.js
> +describe('aria-busy', function() {
An additional test making sure that it returns false if `aria-busy=false`

2022-08-04 16:26 UTC, WilcoFiers requested changes

2022-08-04 16:26 UTC, WilcoFiers commented on lib/checks/aria/aria-busy.json
> +      "fail": "Element does not have aria-busy tag"
```suggestion
      "pass": "Element has aria-busy attribute",
      "fail": "Element has no aria-busy=\"true\" attribute"
```

2022-08-05 15:56 UTC, WilcoFiers commented on lib/checks/aria/aria-busy.json
> +      "pass": "Element has aria-busy attribute",
```suggestion
      "pass": "Element has an aria-busy attribute",
```

2022-08-05 15:58 UTC, WilcoFiers approved these changes

2022-08-05 21:16 UTC, merged