fix(color-contrast): ignore overlapping elements that do not interfere with the background color
dequelabs/axe-core pull request #3583
Opened 2022-08-04 16:47 UTC by straker

This should drastically decrease the number of overlapping element incompletes axe-core generates, especially for anyone who uses Material Button on their site. I moved `findPseudoElement` to it's own function so it could be used in both `color-contrast-evaluate` and `calculateObscuringElement`. 

I also moved `getBackgroundStack` to the top to match our default export style. The main parts of that file change are the addition of `isEmptyElement` that goes with the `isInlineDescendant` check.

Closes issue: #3464

2022-08-17 12:25 UTC, WilcoFiers requested changes

2022-08-17 12:25 UTC, WilcoFiers commented on lib/commons/dom/find-pseudo-element.js
> +    matchPseudoStyle('position', 'absolute') === false
This line works well enough when this was part of the color-contrast-evaluate method, but I'm not so sure about this now that it's in the commons.

2022-08-17 12:25 UTC, WilcoFiers commented on lib/commons/color/get-background-stack.js
> +  const hasPseudoElement = !!findPseudoElement(vNode, {
This method doesn't seem right here. For example, if the pseudo element isn't position:absolute, `hasPsuedoElement` would become false, even if there's a background color, or content, or a bunch of other things on that.

I'm not sure how to fix that, except perhaps maybe have this be "true" unless `content:none` is true for both `:before` and `:after`? I'm not sure that `findPseudoElement` should have been added to `commons`. There are a bunch of things it does that make sense for inside color-contrast-evaluate, but that create problematic gotchas if used in other places.

2022-08-17 12:25 UTC, WilcoFiers commented on test/commons/dom/find-pseudo-element.js
> +            '{ content: ""; width: 100%; height: 100px; background: red; position: absolute; }</style><div class="parent"><div><div id="target" style="height: 100px;"></div></div></div>'
Would you mind putting in a line break into these longer lines?

2025-01-08 20:46 UTC, straker commented
Closing as I don't think we'll get to this any time soon, pr code will still be here if we need it.

2025-01-08 20:46 UTC, closed without merging