feat(is-focusable): account for negative tabindex
dequelabs/axe-core pull request #3609
Opened 2022-08-16 22:37 UTC by dbowling

- add option arg that enables looking for negative tabindex (defaults to false)

references: #3500

2022-08-16 22:54 UTC, straker submitted a review, later dismissed

2022-08-16 22:54 UTC, straker commented on lib/commons/dom/is-focusable.js
> +export default function isFocusable(el, options = { programmatically: false }) {
No need to set the default

```suggestion
export default function isFocusable(el, options = {}) {
```

2022-08-16 22:54 UTC, straker commented on lib/commons/dom/is-focusable.js
> +    parseInt(tabindex, 10) === -1
`-1` is not the only valid negative tabindex value

```suggestion
    parseInt(tabindex, 10) < 0
```

2022-08-16 22:55 UTC, straker commented on lib/commons/dom/is-focusable.js
> +    parseInt(tabindex, 10) === -1
You'll also want to modify one of the tests for another negative value other than `-1`

2022-08-17 10:27 UTC, WilcoFiers requested changes
1. This is not a feature, it's a refactor
2. Please use the option, otherwise you've just added dead code.

2022-08-17 10:27 UTC, WilcoFiers commented on lib/commons/dom/is-focusable.js
> +    return false;
Elements with a negative tabindex are programmatically focucsable.

```suggestionI
    return true;
```

2022-08-24 14:00 UTC, WilcoFiers submitted a review, later dismissed

2022-08-24 14:00 UTC, WilcoFiers commented on test/commons/dom/is-focusable.js
> +        describe('true (default)', function () {
This is kind of a personal preference, but when it comes to boolean options I prefer defaults to be falsey. It's not intuitive (to me) for undefined and true to behave the same, but for false to be different. Much of axe-core works that way, so it's more consistent doing this too.

I propose using `ifProgrammatic` with a falsey default.

2022-08-24 17:39 UTC, dbowling commented
Just documenting a discussion for this PR:

We're going to create a new function and leave isFocusable unchanged. This should drastically simplify future implementations. Also, implementations will go into a new issue as needed to avoid scope creep.

I'll force push the new approach, so I'm resolving all requests for changes now as outdated.

2022-08-24 18:10 UTC, merged

2022-08-24 19:22 UTC, straker commented
We seem to have somehow confused the GitHub UI. This pr was not merged into develop, does [not appear in develops commit history](https://github.com/dequelabs/axe-core/commits/develop), and GitHub even says 0 commits were merged. The commit that says was merged (49ccb00) is [an entirely different pr](https://github.com/dequelabs/axe-core/commit/49ccb007c63cc3f1dce7b82cb7630856fb17605c). Not sure what happened.

<img width="573" alt="Screenshot from GitHub showing: 
dbowling merged 0 commits into develop from 3500-isFocusable-negative-tabindex" src="https://user-images.githubusercontent.com/2433219/186504850-7aa1bb37-d0b4-4e24-aadd-21757eb3ca64.png">