ci: add action to create pr for auto-generated files
dequelabs/axe-core pull request #3620
Opened 2022-08-24 23:25 UTC by straker

We have two files that are automatically generated on build: `doc/rule-descriptions.md` and `locales/_template.json`. These files can easily become out-of-sync when a pull request makes changes to a rule or check metadata file. If the either of these files get suggestions and the suggestions are accepted, the files would need to be rebuilt and redployed to the pr. Most of the time this doesn't happen and the changes aren't applied to the generated files. This causes any new builds on local branches to have new changes from develop.

This action will run the build on pushes to develop and make a pr with the built files if there are changes. You can see it working here: https://github.com/straker/issue-template-tests/pull/22. If there are no changes, the action will fail and not create a pr (as seen here https://github.com/straker/issue-template-tests/actions/runs/2922890704).

2022-08-24 23:27 UTC, straker commented on .github/workflows/update-generated-files.yaml
> +      - name: Create pull pull-requests
I wanted to use a condition to run this step, but [there's currently a bug in action runners](https://github.com/actions/runner/issues/2033) that prevents 3rd party actions from running.

2022-08-26 16:38 UTC, WilcoFiers requested changes
I suggest we do something to avoid opening multiple PRs. Perhaps use a constant branch name. If the branch exists in remote we push the update, if it doesn't then we create the PR. The repo is set up to delete branches after merge, so if there's a remote branch, we can be confident there's a PR.

2022-08-29 18:30 UTC, straker commented on .github/workflows/update-generated-files.yaml
> +        if: ${{ steps.changes.outputs.changes && !steps.branchExists.outputs.exists }}
You can see a working example of using the the step outputs:

- [no changes](https://github.com/straker/issue-template-tests/runs/8076907049?check_suite_focus=true)
- [changes and branch does not exist](https://github.com/straker/issue-template-tests/runs/8077228637?check_suite_focus=true)
- [changes and branch already exists](https://github.com/straker/issue-template-tests/runs/8077261494?check_suite_focus=true)

2022-08-31 16:53 UTC, WilcoFiers approved these changes

2022-08-31 17:07 UTC, merged