Axe Board
dequelabs/axe-core pull request #3661
Opened 2022-09-16 14:31 UTC by balajihambeere

Axe Board is an accessibility testing application for websites and other HTML-based user interfaces. Designed using Axe Core Engine.

<< Describe the changes >>

Closes issue:

2022-09-16 14:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dequelabs/axe-core?pullRequest=3661) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dequelabs/axe-core?pullRequest=3661) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dequelabs/axe-core?pullRequest=3661) it.</sub>

2022-09-17 22:09 UTC, dylanb commented
We will ot merge this until this issue https://github.com/balajihambeere/axe-board/issues/1 has been resolved

2022-09-17 22:10 UTC, dylanb requested changes
change the name of the project to cease violating the registered trademark AXE®

2022-09-18 10:46 UTC, WilcoFiers approved these changes
Very cool project @balajihambeere! Looking forward to see where else you're going to take this.

For the books: I reviewed this PR for security.

2022-09-18 10:48 UTC, merged