Focus trap hidden focus
dequelabs/axe-core pull request #3667
Opened 2022-09-21 21:42 UTC by straker

Closes issue: https://github.com/dequelabs/axe-core/issues/3430

2022-09-22 12:07 UTC, WilcoFiers requested changes

2022-09-22 12:07 UTC, WilcoFiers commented on lib/checks/keyboard/focusable-disabled-evaluate.js
> +    const vNode = getNodeFromTree(related);
I think a refactor is in order to avoid this lookup. We had the virtual nodes of these 15 lines higher.

2022-09-22 12:07 UTC, WilcoFiers commented on lib/checks/keyboard/focusable-not-tabbable-evaluate.js
> +    const vNode = getNodeFromTree(related);
As above.

2022-09-23 13:38 UTC, WilcoFiers commented on lib/checks/keyboard/focusable-disabled-evaluate.js
> +  this.relatedNodes(relatedNodes.map(vNode => vNode.actualNode));
One of these days I'm going to create a PR to just allow virtual nodes here... Not today though.

2022-09-23 13:39 UTC, WilcoFiers approved these changes

2022-09-23 14:15 UTC, merged

2022-09-26 09:36 UTC, padmavemulapati commented
Validated with the latest axe-core develop branch code base,
for the below test scripts: `aria-hidden-focus` rule presenting incomplete results for the,
```
 <!--Incomplete examples-->
  <div aria-hidden="true" id="target">
   <button onfocus="redirectFocus()">button</button>
    </div>
   <!--returns undefined when all focusable controls have onfocus event-->
  <div aria-hidden="true" id="target">
    <a href="/" onfocus="redirectFocus()">First link</a>
  <a href="/" onfocus="redirectFocus()">Second link</a>
    </div>
<!--returns false when some, but not all focusable controls have onfocus events-->
<div aria-hidden="true" id="target">
 <a href="/" onfocus="redirectFocus()">First link</a>
   <a href="/"">Second link</a>
  </div>
  <!--returns undefined when control has 0 width and height and pointer events: none (focus trap bumper-->
  <div id="target" aria-hidden="true" tabindex="0" style="pointer-events: none"></div>

    <!--returns undefined when control has 0 width and height and pointer events: none (focus trap bumper) -->
    <button id="target" aria-hidden="true" style="pointer-events: none; width: 0; height: 0; margin: 0; padding: 0; border: 0"></button>'

  ```
failing at the scripts:
```
<!--failure examples-->
  <div aria-hidden="true">
    <a href="/" style="position:absolute; top:-999em" onfocus="document.querySelector('input').focus()">First link</a>
  </div>
  <input />
  <fieldset id="target" disabled aria-hidden="true"><legend><input /></legend></fieldset>'
  <fieldset id="target" aria-hidden="true"><input /></fieldset>
  <div id="target" aria-hidden="true"><a href="/" style="position:absolute; top:-999em">Link</a></div>'
  <div id="target" aria-hidden="true"><input type="text" aria-disabled="true"/></div>
  <div aria-hidden="true"><a id="target" href="">foo</a><button>bar</button></div>'
```
also validated for the pass scripts:
```
<!--Pass examples-->
    <div aria-hidden="true"></div>
    <button tabindex="-1">Some button</button>
  </div>
  <p id="target" aria-hidden="true">Some text</p>
  <div id="target" aria-hidden="true"><a href="/" style="display:none">Link</a></div>
  <input id="target" disabled aria-hidden="true" /> 
  <fieldset id="target" disabled aria-hidden="true"><input /></fieldset> 
```
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/47409579/192243279-c0053800-1fb9-4adf-96ef-a63a0ba2dd57.png">