Create el.json
dequelabs/axe-core pull request #3836
Opened 2022-12-19 09:57 UTC by sl45sms

Greek Translation (el)

2022-12-19 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dequelabs/axe-core?pullRequest=3836) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dequelabs/axe-core?pullRequest=3836) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dequelabs/axe-core?pullRequest=3836) it.</sub>

2023-01-03 15:42 UTC, WilcoFiers commented
@sl45sms Wow thank you! Apologies for the delayed response. This one slipped through in the vacation. I'll need to find someone who can help us review this, which from past experience can take a while. So heads up on that.

2023-02-20 18:49 UTC, WilcoFiers commented
Just another quick ping to let you know we haven't forgotten. As I warned this can be slow, but I'm still working on it!

2023-02-21 06:35 UTC, sl45sms commented
> Just another quick ping to let you know we haven't forgotten. As I warned this can be slow, but I'm still working on it!

Great, not rush, take the time as needed, thanks a lot.

2023-08-29 22:09 UTC, straker requested changes
Apologies for the long delay in getting this reviewed. We're hoping to pull it into the 4.8 release happening soon. Thanks again for taking the time to translate.

Below are a few questions and suggestions. Importantly some of the wording has changed since you made this translation and I wanted to point that out to see if you wanted to update the wording to reflect the current values.

2023-09-21 09:35 UTC, sl45sms commented on locales/el.json
> +        "description": "Διασφαλίζει ότι κάθε ARIA σε κουμπί,σύνδεσμο ή στοιχείο μενού έχει ένα προσβάσιμο όνομα",
it is clear for the Greek programmers, but for compatibility reasons I will add them.

2023-09-21 09:48 UTC, sl45sms commented on locales/el.json
> +        "help": "Τα στοιχεία πρέπει να έχουν επαρκή χρωματική αντίθεση"
i will do that.

2023-09-21 09:54 UTC, sl45sms commented on locales/el.json
> +        "pass": "Δεν υπάρχει χαρακτηριστικό arria-hidden στο σώμα του εγγράφου",
fixed

2023-09-21 09:57 UTC, sl45sms commented on locales/el.json
> +          "fgOnShadowColor": "Το στοιχείο έχει ανεπαρκή χρωματική αντίθεση ${data.contrastRatio} μεταξύ του χρώματος του προσκηνίου και του χρώματος σκιάς (χρώμα προσκηνίου: ${data.fgColor}, χρώμα σκ
fixed

2023-09-21 09:57 UTC, sl45sms commented on locales/el.json
> +          "fgOnShadowColor": "Το στοιχείο έχει ανεπαρκή χρωματική αντίθεση ${data.contrastRatio} μεταξύ του χρώματος προσκηνίου και σκιάς (χρώμα προσκηνίου: ${data.fgColor}, χρώμα σκιάς κειμένου: ${d
fixed

2023-09-21 10:10 UTC, sl45sms commented on locales/el.json
> +      "target-offset": {
changed

2023-09-21 10:11 UTC, sl45sms commented on locales/el.json
> +          "partiallyObscuredNonTabbable": "Ο στόχος έχει ανεπαρκές μέγεθος επειδή είναι μερικώς καλυμμένος από έναν γείτονα με αρνητικό tabindex (το μικρότερο διάστημα είναι ${data.width}px επί ${dat
fixed

2023-09-21 10:17 UTC, sl45sms commented on locales/el.json
> +        "description": "Διασφαλίζει ότι τα χαρακτηριστικά ARIA επιτρέπονται για το ρόλο του στοιχείου",
changed

2023-09-25 17:29 UTC, straker commented
@sl45sms Am I correct to assume that this PR is ready for review again with all your updates?

2023-09-25 18:32 UTC, sl45sms commented
> @sl45sms Am I correct to assume that this PR is ready for review again with all your updates?

Yes please, review the updates. Thanks.

2023-10-09 17:50 UTC, ibrahimosman1127 commented on locales/el.json
> +        "description": "Διασφαλίζει ότι τα χαρακτηριστικά ARIA επιτρέπονται για το ρόλο του στοιχείου",
Thanks

2023-11-28 15:24 UTC, straker approved these changes

2023-11-28 15:24 UTC, straker commented
Thanks for the translations! Approved for security

2023-12-15 15:41 UTC, merged