update polish language
dequelabs/axe-core pull request #3989
Opened 2023-04-16 18:41 UTC by zwiastunsw

update to new version

2023-08-21 16:54 UTC, WilcoFiers requested changes
@zwiastunsw I left a couple minor comments, please have a look and let me know if this is correct.

2023-08-21 16:54 UTC, WilcoFiers commented on locales/pl.json
> +        "shadowOnBgColor": "Element ma niewystarczający kontrast kolorów: of ${data.contrastRatio} pomiędzy kolorem cienia a kolorem tła (text-shadow color: ${data.shadowColor}, background color: ${d
Should those colons (`:`)  be after "kontrast kolorów"?

2023-08-29 10:37 UTC, WilcoFiers requested changes
Two very minor comments. The rest looks excellent.

2023-08-29 10:37 UTC, WilcoFiers commented on locales/pl.json
> +      "help": "Element z atrybutem \"role=text\" nie może mieć potomków przyjmujących fokus."
That should probably be like this. We only recently caught this issue in the original.

```suggestion
      "help": "Element z atrybutem role=\"text\" nie może mieć potomków przyjmujących fokus."
```

2023-08-31 02:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dequelabs/axe-core?pullRequest=3989) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/dequelabs/axe-core?pullRequest=3989) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: zwiastunsw<br/>:x: wojsmol<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dequelabs/axe-core?pullRequest=3989) it.</sub>

2023-09-05 10:08 UTC, merged

2023-09-12 15:00 UTC, zwiastunsw commented
Thx