Update: add meter to allowed roles for named img
dequelabs/axe-core pull request #4055
Opened 2023-06-15 15:49 UTC by scottaohara

closes #4054

as stated in the PR title, this adds the meter element to be an allowed role for the img element when it is provided an accessible name.

2023-06-15 18:36 UTC, straker requested changes
Thanks for the pr. Would you be able to add a test for this is [test/integration/aria-allowed-role.html](https://github.com/dequelabs/axe-core/blob/develop/test/integration/rules/aria-allowed-role/aria-allowed-role.html#L247-L265). Just adding an image tag with the new role and and id that will need to be added to the companion json file pass section.

2023-06-15 18:56 UTC, scottaohara commented
added

2023-06-15 19:20 UTC, straker commented
Thanks. The element will need an `id` attribute and then the `id` will need to be added to the companion [aria-allowed-role.json](https://github.com/dequelabs/axe-core/blob/develop/test/integration/rules/aria-allowed-role/aria-allowed-role.json#L4) file to the `passes` section (that should resolve the tests).

2023-06-16 13:19 UTC, scottaohara commented on test/integration/rules/aria-allowed-role/aria-allowed-role.html
> +<img src="#" role="meter" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" alt="test">
```suggestion
<img src="#" role="meter" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" alt="test" id="pass-img-valid-role-meter">
```

2023-06-16 14:23 UTC, straker approved these changes
Awesome! Thanks for doing that. 

Reviewed for security.

2023-06-16 14:25 UTC, merged