feat: add rule aria-deprecated-role
dequelabs/axe-core pull request #4074
Opened 2023-06-29 21:49 UTC by straker

Split out `aria-deprecated-role` from `aria-roles` into it's own rule.

Closes: #4069

2023-06-29 21:50 UTC, straker commented on package.json
> +    "inquirer": "^8.2.5",
This was needed to run the run generator. Not sure when it was removed.

2023-06-30 09:16 UTC, WilcoFiers submitted a review, later dismissed

2023-06-30 09:16 UTC, WilcoFiers commented on lib/rules/aria-deprecated-role.json
> +  "tags": ["cat.aria", "wcag2a", "wcag412"],
Add the EN tags

2023-06-30 09:16 UTC, WilcoFiers commented on test/integration/rules/aria-roles/aria-roles.html
> -  <div role="directory" id="fail16">ok</div>
Maybe move these to passed?

2023-06-30 09:16 UTC, WilcoFiers commented on test/integration/rules/aria-deprecated-role/aria-deprecated-role.html
> +<!-- deprecated roles-->
Probably add some passed examples.

2023-07-04 10:02 UTC, WilcoFiers approved these changes

2023-07-07 12:11 UTC, WilcoFiers requested changes
Nitpick

2023-07-07 12:11 UTC, WilcoFiers commented on lib/rules/aria-deprecated-role.json
> +    "help": "ARIA roles used must not be deprecated"
I think you mean this:

```suggestion
    "help": "Deprecated ARIA roles must not be used"
```

2023-07-10 14:17 UTC, WilcoFiers requested changes

2023-07-10 14:17 UTC, WilcoFiers commented on locales/_template.json
> +      "help": "ARIA roles used must not be deprecated"
I don't think you reran the build script?

2023-07-10 14:39 UTC, WilcoFiers approved these changes

2023-07-10 16:20 UTC, merged