feat(d.ts): improve axe.d.ts types
dequelabs/axe-core pull request #4081
Opened 2023-07-05 18:19 UTC by hamax

Improve axe.d.ts types based on what we found was missing/incorrect and was needed in our code. I added more details for each change in commit messages (I tried to verify that each change is correct by looking at axe internals). Some of the issues were introduced with a recent update in #3966, which prompted me to look into this more.

2023-07-12 16:59 UTC, WilcoFiers requested changes
Thanks for opening this PR. I am really curious what you are using these methods for.

2023-07-12 16:59 UTC, WilcoFiers commented on axe.d.ts
> +    getRoleType: (role: string) => string | null;
```suggestion
    getRoleType: (role: string | Element | VirtualNode | null) => string | null;
```

2023-07-12 16:59 UTC, WilcoFiers commented on axe.d.ts
> +    isNativelyFocusable: (node: Element) => boolean;
```suggestion
    isFocusable: (node: Element | VirtualNode) => boolean;
    isNativelyFocusable: (node: Element | VirtualNode) => boolean;
```

2023-07-12 16:59 UTC, WilcoFiers commented on axe.d.ts
> +    accessibleText: (element: Element, inLabelledByContext?: boolean) => string;
```suggestion

  type AccessibleTextOptions = {
    inControlContext?: boolean
    inLabelledByContext?: boolean
  }
  
  interface Text {
    accessibleText: (element: Element, options?: AccessibleTextOptions) => string;
```

2023-07-12 16:59 UTC, WilcoFiers commented on axe.d.ts
> +  interface EvaluateResult {
This is what we've been calling this internally:

```suggestion
  interface AfterResult {
```

2023-07-18 15:21 UTC, hamax commented
Thanks, I amended the commits with suggestions (+ prettier formatting).

> Thanks for opening this PR. I am really curious what you are using these methods for.

Mostly for custom rules/checks and capturing additional debug information for nodes in results. I think it makes sense for utils commonly used from checks to be available.

2023-07-19 10:05 UTC, WilcoFiers approved these changes

2023-07-19 10:06 UTC, WilcoFiers commented
✅  Reviewed for security.

2023-07-19 10:08 UTC, merged

2023-07-19 10:09 UTC, WilcoFiers commented
Thank you again for your contribution @hamax!