fix(access-name): get name from header elements
dequelabs/axe-core pull request #4097
Opened 2023-07-20 11:57 UTC by WilcoFiers

The content of landmarks and other elements that have "name from author" should not be ignored when referenced by aria-labelledby or another label. 

This is a bug, where axe was inconsistent with the accessible name spec. Specifically, [step F](https://www.w3.org/TR/accname-1.1/#step2F):
> if the current node's role allows name from content, or if the current node is referenced by aria-labelledby, aria-describedby, or is a native host language text alternative element (e.g. label in HTML), or is a descendant of a native host language text alternative element

Previously axe-core was only considering the first part of this sentence, and skipping name from author elements while following aria-labelledby and `<label>` IDREFs. This was a problem on dialogs (as the issue reported), but had broader implications too. Notably, column and rowheaders in a table could not be referenced with aria-labelledby.

That created a second problem; Elements with a value (like select and progressbar) should never use name from content. I had to add a condition in for that. I ended up testing the use of element values  in names again. This improved a good bit, and so now only the value of progressbar still can't be relied on to give an accessible name.

Closes: #3752

2023-07-20 11:59 UTC, WilcoFiers commented on test/integration/rules/label/label.html
> -    <label>
This label does nothing, and fail24 is not tested by this rule; this is not the select-name rule.

2023-07-24 18:14 UTC, straker requested changes

2023-07-24 18:14 UTC, straker commented on lib/commons/text/unsupported.js
> +  accessibleNameFromFieldValue: ['progressbar']
Should we have a test for `combobox` and `listbox` now being supported? I see you changed a test from `combobox` to `listbox` but not any added tests to show they are supported.

2023-08-08 15:25 UTC, straker approved these changes

2023-08-08 16:12 UTC, merged