fix(aria-allowed-attr): pass aria-expanded on checkbox & switch
dequelabs/axe-core pull request #4110
Opened 2023-07-31 13:14 UTC by WilcoFiers

WAI-ARIA 1.3 has proposed to dramatically change which roles allow aria-expanded. Per this PR, `checkbox` and `switch` now allow this attribute. Quite a few more roles no longer allow `aria-expanded`.

I've opened up an issue requesting that ARIA 1.3 deprecate aria-expanded on those roles, instead of simply removing them. I think simply removing them would create a lot of unnecessary friction. If the W3C decides not to stay backward compatible we may have to figure out a different way to present this, but by far the best solution here would be to use deprecation, which is what they've also done in other places. See https://github.com/w3c/aria/issues/1990

Closes #3339, closes #3343

2023-08-01 22:33 UTC, straker requested changes

2023-08-01 22:33 UTC, straker commented on lib/standards/aria-roles.js
> +    allowedAttrs: ['aria-expanded'],
Did you mean to add this?

```suggestion
```

2023-08-02 13:43 UTC, straker approved these changes

2023-08-07 19:04 UTC, dbjorge approved these changes

2023-08-08 12:35 UTC, merged