chore: Update local de.json
dequelabs/axe-core pull request #4249
Opened 2023-11-17 15:18 UTC by EvilKarter

I have written a small script, that synchronizes the offered _template.json in locales with all languages. 
If the _template.json file is incomplete, then this PR is also incomplete

I have added to the translation:
- new rules 
- new checks 
- added and removed child entries of rules and checks

I have noticed that all the locales provided are missing entries. 
However, I cannot translate them (with the exception of German)

Closes: #4248

2023-11-27 22:36 UTC, straker requested changes

2023-11-28 07:48 UTC, EvilKarter commented
@straker Many thanks for the feedback. I have adopted your suggested changes. I have also searched for all translations of "have discernible text" and harmonised them

2023-11-28 15:08 UTC, straker approved these changes

2023-11-28 15:09 UTC, straker commented
Approved for security

2023-11-28 15:11 UTC, merged