fix: Add LICENSE-3RD-PARTY.txt file
dequelabs/axe-core pull request #4304
Opened 2024-01-22 12:24 UTC by WilcoFiers

Axe-core needs to include the copyright and licenses of third-party software.

2024-01-22 14:48 UTC, keith-rhodes-0723 approved these changes
looks like it has correct info.

2024-01-24 05:11 UTC, dbjorge requested changes

2024-01-24 16:44 UTC, WilcoFiers commented on LICENSE-3RD-PARTY.txt
> +-----------------------------------------------------------------------------
Check for transitive dependencies @WilcoFiers

2024-01-25 18:53 UTC, dbjorge requested changes

2024-01-25 18:53 UTC, dbjorge commented on LICENSE-3RD-PARTY.txt
> +  - memoizee; Copyright (c) 2012-2018, Mariusz Nowak, @medikoo, medikoo.com
`memoizee` has the following transitive runtime dependencies that need to be reflected in this file:

```
d
es5-ext
es6-iterator
es6-symbol
es6-weak-map
event-emitter
ext
is-promise
lru-queue
next-tick
timers-ext
type
```

2024-01-31 20:50 UTC, dbjorge approved these changes

2024-02-01 10:42 UTC, merged