feat(aria-prohibited-attr): add support fallback role
dequelabs/axe-core pull request #4325
Opened 2024-02-05 07:32 UTC by takenspc

This PR adds fallback role support to `aria-prohibited-attr`. For example, `<div role="foo img" aria-label="...">` is legal.

At this time, I do not plan to add fallback roles support for other checks.

Related:

* https://github.com/dequelabs/axe-core/issues/3768

Closes:

2024-02-07 17:10 UTC, straker commented
Thanks for the pr. Unfortunately with axe-core quickly approaching we won't be able to look at this any time soon. After axe-con we'll be able to revisit this again.

2024-02-08 00:39 UTC, takenspc commented
> Thanks for the pr. Unfortunately with axe-con quickly approaching we won't be able to look at this any time soon. After axe-con we'll be able to revisit this again.

Thank you for providing the information. I wish you a successful event, as in previous years. Please let me know if you need any changes are necessary.

2024-03-05 10:04 UTC, WilcoFiers requested changes
Would you mind adding one or two test cases to `test/integration/rules/aria-prohibited-attr/aria-prohibited-attr.html` and its `.json` file as well?

2024-03-05 10:04 UTC, WilcoFiers commented on test/checks/aria/aria-prohibited-attr.js
> +  it('should not allow elements that have an invalid role', function () {
```suggestion
  it('should not allow aria-label on divs that have an invalid role', function () {
```

2024-03-05 10:04 UTC, WilcoFiers commented on test/checks/aria/aria-prohibited-attr.js
> +  it('should allow elements that have fallback roles', function () {
```suggestion
  it('should allow aria-label on divs with a valid fallback role', function () {
```

2024-03-05 10:04 UTC, WilcoFiers commented on test/checks/aria/aria-prohibited-attr.js
> +  it('should not allow elements that have multiple invalid roles', function () {
```suggestion
  it('should not allow aria-label on divs with no valid fallback roles', function () {
```

2024-03-05 11:36 UTC, takenspc commented
@WilcoFiers 

Thank you for your review.

> Would you mind adding one or two test cases to `test/integration/rules/aria-prohibited-attr/aria-prohibited-attr.html` and its `.json` file as well?

I have added a few tests to `test/integration/rules/aria-prohibited-attr/aria-prohibited-attr.html` in https://github.com/dequelabs/axe-core/pull/4325/commits/b405042a5b58e6a2b88192538d6119678c44bf7e.

Although I need to update this branch to pass CI tests, it may be better to wait until https://github.com/dequelabs/axe-core/pull/4354 is merged.

2025-04-10 22:39 UTC, straker approved these changes
Sorry that this took so long! Seems it fell through the cracks. I've gone ahead and merged developed and resolved the changes, so approving and merging. Thanks again for the work.

Approved for security.

2025-04-10 22:42 UTC, merged