feat(aria-required-children): deprecate aria-busy check, improve failure messages
dequelabs/axe-core pull request #4347
Opened 2024-02-28 21:57 UTC by dbjorge

Removes the confusing aria-busy message from aria-required-children failures (which we've seen several reports of).

Also fixes a false negative (the new #fail13 integration test), which was related but hasn't been reported before.

Marks the separate `aria-busy` check as deprecated since no rule uses it after this change.

@straker , note that this will have a logical merge conflict with the PRs adding new translations you're working on

Closes: #4340

2024-02-28 23:03 UTC, dbjorge commented on locales/da.json
> +      "pass": {
I know we normally don't update translations with this sort of change, but I thought it made sense to fix the structure here - with these updates, `npx grunt translate` will preserve the old translations, and without these updates, it'll eat the existing translations and replace them with english.

2024-03-04 13:22 UTC, WilcoFiers requested changes

2024-03-04 13:22 UTC, WilcoFiers commented on lib/checks/aria/aria-busy.json
> +  "deprecated": true,
Deprecation should probably go into its own PR so it's a separate line in the changelog.

2024-03-05 09:49 UTC, WilcoFiers approved these changes

2024-03-05 15:51 UTC, merged