feat: adding the wcag 412 tag to the aria hidden body rule
dequelabs/axe-core pull request #4349
Opened 2024-02-29 04:43 UTC by CBID2

<< Describe the changes >>
This PR adds the `wcag412` tag to the aria-hidden-body rule, making it easier for the testing engine to detect issues.

Closes #4315

2024-03-03 21:50 UTC, CBID2 commented
Hi @straker! :) My PR is ready for review! :)

2024-03-04 13:26 UTC, WilcoFiers requested changes
Build is failing because of this. Also please update the PR title, you're adding wcag131, not 412.

2024-03-04 13:26 UTC, WilcoFiers commented on lib/rules/aria-hidden-body.json
> +    "EN-9.4.1.2"
```suggestion
    "EN-9.1.3.1",
    "EN-9.4.1.2"
```

2024-03-04 13:27 UTC, CBID2 commented
> wcag131

Done @WilcoFiers

2024-03-05 09:50 UTC, WilcoFiers approved these changes

2024-03-05 09:51 UTC, WilcoFiers commented
Reviewed for security.

2024-03-05 09:52 UTC, merged