fix(color-contrast): handle text that is outside `overflow: hidden` ancestor
dequelabs/axe-core pull request #4357
Opened 2024-03-05 17:12 UTC by straker

Closes: #4253

2024-03-07 18:14 UTC, WilcoFiers submitted a review, later dismissed

2024-03-12 15:23 UTC, straker commented on lib/commons/dom/get-visible-child-text-rects.js
> +      : filterHiddenRects([nodeRect], overflowHiddenNodes);
Decided to leave this in as a failsafe though it technically shouldn't be needed anymore

2024-03-12 15:43 UTC, WilcoFiers requested changes
Editorial

2024-03-12 15:43 UTC, WilcoFiers commented on lib/rules/color-contrast-matches.js
> +    const overlapps = visuallyOverlaps(rect, node);
```suggestion
    const overlaps = visuallyOverlaps(rect, node);
```

2024-03-12 15:43 UTC, WilcoFiers commented on lib/rules/color-contrast-matches.js
> +      return overlapps;
```suggestion
      return overlaps;
```

2024-03-12 15:43 UTC, WilcoFiers commented on lib/rules/color-contrast-matches.js
> +  const overflowNodes = getOverflowHiddenAncestors(virtualNode);
How about:

```suggestion
  const clippingAncestors = getOverflowHiddenAncestors(virtualNode);
```

2024-03-12 15:53 UTC, WilcoFiers approved these changes

2024-03-12 15:56 UTC, merged