feat(color): add luminosity, saturation, clip, normalize, add, and scale functions
dequelabs/axe-core pull request #4366
Opened 2024-03-08 18:46 UTC by straker

Decided to move the Color improvements from https://github.com/dequelabs/axe-core/pull/4365/files into their own PR. For the naming I used the names associated with Vectors as they also have to deal with normalizing values between 0-1. Also Googling "normalize RGB" brings up results for RGB between 0-1, so it makes sense to use the naming.

This also fixes the `clip` bug mentioned in https://github.com/dequelabs/axe-core/pull/4365/files#r1517706612

No QA needed

2024-03-08 18:53 UTC, straker commented on lib/commons/color/color.js
> +    if (red instanceof Color) {
Now we can create a new color from another one:

```js
const color = new Color(0,0,0);
const color2 = new Color(color);
```

2024-03-11 12:18 UTC, WilcoFiers requested changes

2024-03-11 19:44 UTC, straker commented on lib/commons/color/color.js
> +    );
Maybe a new class? An object wouldn't have all the functions attached to handling the fraction components. After thinking about the problem more I don't like the idea of using settings/getters to tie the two together. 

The problem is that values outside the [range of 0-1 are allowed](https://drafts.csswg.org/css-color/#color-function) and while outside the color gamut are not invalid channel values. This means we can't easily translate a value of 1.1 back to RGB as 255 is the maximum. 

What it really seems is that we need two different similar yet different color objects. We have the RGB Color (what it is now) and then need a separate Color to represent 0-1 and all it's functions (functions that also don't really work when applied to an RGB color either).

2024-03-11 21:52 UTC, straker commented on lib/commons/color/color.js
> +    );
Decided to mimic how Colorjs.io does this by using color coordinates (mapped to `r`, `g`, `b`), also called color channels.

2024-03-11 21:54 UTC, straker commented on .eslintrc.js
> +    ecmaVersion: 2023
Allows us to use private properties and functions in classes (supported by babel).

2024-03-11 21:56 UTC, straker commented on lib/commons/color/color.js
> -    // Colorjs currently does not support rad or turn angle values
[Colorjs 0.5.0](https://github.com/color-js/color.js/releases/tag/v0.5.0) now fully supports grad, rad, and turn so we don't need to do this anymore.

2024-03-11 21:57 UTC, straker commented on lib/commons/color/color.js
> +  #add(value) {
Nothing outside of the color class should add a value to the color components.

2024-03-12 14:29 UTC, WilcoFiers approved these changes

2024-03-12 19:09 UTC, merged

2024-04-03 09:50 UTC, evelynmcr commented
Hi @WilcoFiers and @straker - I've raised a bug [here ](https://github.com/dequelabs/axe-core-nuget/issues/169) which I think could potentially relate to this change? Would you mind taking a look? Thanks!