test: fix flakiness in rerun integration test
dequelabs/axe-core pull request #4598
Opened 2024-10-04 21:13 UTC by dbjorge

This addresses some test flakiness in `/test/integration/rerun/rerun.js` which has caused ~4 e2e test failures in CI builds in the last 3 weeks. It manifests as a timeout because the test uses assertions within callbacks to `axe.run` without propogating errors to the `done` callback; this addresses that similarly to other tests using the run callback pattern, which should cause new errors in this test to report the actual assertion failure instead of just timing out.

I wasn't able to locally repro the actual failure, but I think a good guess as to why it's failing flakily is the same issue we saw with other tests doing deep comparison of axe result objects (testEnvironment differing between nearby scans due to windowHeight differences). I addressed that by reusing the test util we added for doing result comparison.

I didn't want to hardcode knowledge of the testEnvironment thing into yet another individual test case, so I also refactored the test utility to move that knowledge into one location with a comment explaining it.

2024-10-04 21:40 UTC, straker requested changes
Need to just remove the locale file and should be good to approve

2024-10-04 22:12 UTC, dbjorge commented on locales/ru.json
> +      "pass": "Элемент может быть сфокусирован.",
The autoformatter pulled it in on its own

2024-10-05 03:05 UTC, stephenmathieson commented on test/testutils.js
> +      // inconsistencies in windowHeight for otherwise-identical scans.
Thank you for adding this comment. I didn't understand why we were ignoring it before 👍

2024-10-07 11:02 UTC, WilcoFiers approved these changes

2024-10-07 16:20 UTC, merged