Update rule-descriptions.md
dequelabs/axe-core pull request #4633
Opened 2024-11-08 20:06 UTC by mgifford

Good to put in a link to ACT

Just adding a link as it wasn't clear to someone new to this.

2024-11-11 10:55 UTC, WilcoFiers requested changes
Good suggestion. This is a generated file though. We'll have to make the change here in order for it not to get clobbered next time someone updates a rule:

https://github.com/dequelabs/axe-core/blob/develop/build/configure.js#L19

2025-01-08 20:52 UTC, straker commented
@mgifford any update on this pr?

2025-01-09 13:44 UTC, mgifford commented
@straker I think this is waiting for the next build. Something @WilcoFiers would have more influence over. I'm just a very satisfied user.

2025-01-11 19:12 UTC, mgifford commented
Ok, @WilcoFiers I moved the patch. Hopefully that works.

2025-01-20 15:31 UTC, straker approved these changes
Awesome, thanks for the pr.

Reviewed for security.

2025-01-20 15:32 UTC, merged