refactor(#4632): correct tabindex parsing logic
dequelabs/axe-core pull request #4637
Opened 2024-11-11 20:59 UTC by ahmedhalac

Ensures tabindex is correctly parsed as an integer using regex instead of parseInt to comply with HTML standards.

Related to #4632

2024-11-12 10:42 UTC, WilcoFiers requested changes
This is a good start, but I think we can do a little better. Going over the code base, it looks like axe has an awful lot of places where it's parsing tabindex. I think it would be better if we put the code for this in one place. Normally we'd do this in a `commons` function, but because one of the places is in core, we'll need to do this in `core/utils`. So how about this:

In `lib/core/utils/` create a file `parse-tabindex.js` with a `parseTabindex` function that accepts either a string or null. And which returns an integer if the string is a valid tabindex value, or null if not valid or if the value is null. This would need tests in a new `test/core/utils/parse-tabindex.js`. 

This function could then be used in the following files, instead of the current ad-hoc methods:
- `lib/checks/keyboard/focusable-no-name-evaluate.js`
- `lib/checks/keyboard/no-focusable-content-evaluate.js`
- `lib/checks/keyboard/tabindex-evaluate.js`
- `lib/commons/dom/get-tabbable-elements.js`
- `lib/commons/dom/inserted-into-focus-order.js`
- `lib/commons/dom/is-focusable.js`
- `lib/commons/dom/is-in-tab-order.js`
- `lib/core/base/context/create-frame-context.js`
- `lib/rules/autocomplete-matches.js`
- `lib/rules/no-negative-tabindex-matches.js`

2024-11-15 16:06 UTC, WilcoFiers requested changes
This is looking great! The change required a few additional updates, this is looking really good.

2024-11-15 16:06 UTC, WilcoFiers commented on lib/checks/keyboard/focusable-no-name-evaluate.js
>    if (!inFocusOrder) {
This is essentially just `isInTabOrder`. Let's use that.

```suggestion
  if (!isInTabOrder(virtualNode)) {
```

2024-11-15 16:06 UTC, WilcoFiers commented on lib/checks/keyboard/focusable-no-name-evaluate.js
> +import { parseTabindex } from '../../core/utils';
```suggestion
import { isInTabOrder } from '../../commons/dom';
import { accessibleTextVirtual } from '../../commons/text';
```

2024-11-19 21:46 UTC, ahmedhalac commented on lib/rules/autocomplete-matches.js
> +  if (tabIndex < 0 && role) {
Fixed. Please review now.

2024-11-20 11:08 UTC, WilcoFiers approved these changes
This is looking great. @ahmedhalac thank you very much for the contribution!

For the books: I reviewed this PR for security.

2024-11-25 12:36 UTC, merged